### ISSUE TITLE
Fails to run on macOS 10.12.3

### ISSUE THREAD

**Issue by noofherder** [fengtan/sophie#1]
$ java -jar sophie-1.2.0-macosx-with-dependencies.jar 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no swt-carbon-3346 or swt-carbon in swt.library.path, java.library.path or the jar file
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:219)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:151)
	at org.eclipse.swt.internal.C.<clinit>(C.java:21)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:943)
	at org.eclipse.swt.widgets.Display.create(Display.java:937)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:119)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:749)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:740)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1386)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:256)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:249)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:202)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:140)
	at com.github.fengtan.sophie.Sophie.main(Sophie.java:76)

**Comment by fengtan** [comment]
Seems to be related:
 * http://stackoverflow.com/questions/6460274/swt-maven-eclipse-java-lang-unsatisfiedlinkerror-no-swt-carbon-3346-or-sw
 * http://stackoverflow.com/questions/22935500/swt-application-is-running-from-eclipse-ide-not-running-when-i-create-a-jar-via

Are you using a 32 bit or a 64 bit JRE ?
Did you compile the jar yourself ?
What if you execute the command with the `-d32` flag as mentioned in one of the links above ?

**Comment by janhoy** [comment]
Got exactly the same. Nobody still runs 32bit java on their Mac :)
The only way forward is to port your app to using Cocoa instead of Carbon, since Cocoa supports 64bit on macos, see https://www.eclipse.org/swt/macosx/

**Comment by noofherder** [comment]
Thanks for the responses guys.
I tried -d32, but it's not supported on the standard macOS JVM, and I don't want to start installing custom JVMs to run this. Carbon is pretty ancient; as Jan says the thing to do is port to Cocoa.

Incidentally we're working on a REST/React Solr index browser - https://github.com/flaxsearch/marple (very much early days, though)

**Comment by fengtan** [comment]
OK thanks for the investigation @janhoy

From what I read on the web, the port of SWT to Cocoa was made in SWT 3.5
https://www.eclipse.org/swt/R3_5/plan.html
https://www.eclipse.org/swt/cocoaport.php

I have updated the dependencies to use SWT 4.3 and made a new release https://github.com/fengtan/sophie/releases/tag/1.2.1

The app looks similar in Linux and Windows -- hopefully this also works on a Mac.

@noofherder thanks for pointing that out ! I am actually looking for alternatives to Sophie.

**Comment by janhoy** [comment]
Thanks for the quick reply.
I got it working, although not with a simple `java -jar` command, which resulted in

    $ java -jar target/sophie-1.2.1-macosx-with-dependencies.jar 
    ***WARNING: Display must be created on main thread due to Cocoa restrictions.
      Exception in thread "main" org.eclipse.swt.SWTException: Invalid thread access
  	at org.eclipse.swt.SWT.error(Unknown Source)
  	at org.eclipse.swt.SWT.error(Unknown Source)
  	at org.eclipse.swt.SWT.error(Unknown Source)
  	at org.eclipse.swt.widgets.Display.error(Unknown Source)
  	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
  	at org.eclipse.swt.widgets.Display.create(Unknown Source)
  	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
  	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
  	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
  	at org.eclipse.swt.widgets.Display.getDefault(Unknown Source)
  	at org.eclipse.swt.widgets.Shell.<init>(Unknown Source)
  	at org.eclipse.swt.widgets.Shell.<init>(Unknown Source)
  	at org.eclipse.swt.widgets.Shell.<init>(Unknown Source)
  	at org.eclipse.swt.widgets.Shell.<init>(Unknown Source)
  	at com.github.fengtan.sophie.Sophie.main(Sophie.java:76)

The cure was to start the app with command

    java -XstartOnFirstThread -jar target/sophie-1.2.1-macosx-with-dependencies.jar 

Perhaps you could include a shell script `sophie-start.sh` which does the right think for Linux and macOS?

**Comment by fengtan** [comment]
Sounds like a good idea, thanks again @janhoy.
The -XstartOnFirstThread option does not seem to be valid on Linux:

    $ java -XstartOnFirstThread -jar target/sophie-1.2.1-linux-with-dependencies.jar
    Unrecognized option: -XstartOnFirstThread
    Error: Could not create the Java Virtual Machine.
    Error: A fatal exception has occurred. Program will exit.

So I have pushed a shell script `sophie-start.sh` that conditionally sets the flag depending on the OS: 2e95b14b2374d6a16f2097fe6c1188b4b9cc8f25. Hopefully this works on all operating systems.
